"""hash de contenido en manuales

Anade manuales.contenido_hash (SHA-256 del PDF) para que subir dos veces el
mismo fichero con nombres distintos deje de crear dos manuales. Asi llegaron a
existir siete copias identicas de la guia de wifi, que devolvia siete veces el
mismo resultado en cada busqueda.

La columna nace NULL en las filas existentes: el sincronizador la rellena en el
siguiente arranque, cuando ya tiene el fichero abierto para leerlo. No se hace
aqui porque una migracion no deberia depender de que los PDF esten en disco.

Revision ID: 31314c06dfbc
Revises: eec0dc7833f3
Create Date: 2026-09-14 10:11:43.136480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31314c06dfbc'
down_revision: Union[str, Sequence[str], None] = 'eec0dc7833f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manuales', sa.Column('contenido_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_manuales_contenido_hash'), 'manuales', ['contenido_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manuales_contenido_hash'), table_name='manuales')
    op.drop_column('manuales', 'contenido_hash')
    # ### end Alembic commands ###
