"""grupos de incidencia

Revision ID: 3f514b913e75
Revises: b1f4c2d93e77
Create Date: 2026-09-11 16:05:50.690400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f514b913e75'
down_revision: Union[str, Sequence[str], None] = 'b1f4c2d93e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Los 9 grupos salen del analisis de las 119 incidencias reales de
# data/sat/Incidencias.xlsx. El numero entre parentesis es cuantas incidencias
# respaldan cada uno. Ver docs/G2_TAXONOMIA_GRUPOS.md.
GRUPOS_INICIALES = [
    ("VINCULACION", "Vinculacion y emparejamiento", "Alta del dispositivo, emparejamiento BLE/Wi-Fi y provisioning (41)", 10),
    ("CONECTIVIDAD", "Conectividad y red", "Enlace Wi-Fi, router, banda 2.4 GHz y conexion con la nube (36)", 20),
    ("GESTUAL", "Control gestual", "Deteccion del gesto, sensibilidad y bloqueos al accionar (31)", 30),
    ("APP", "Aplicacion movil", "Interfaz, cuenta, programaciones y comportamiento de la app (28)", 40),
    ("PULSADOR", "Pulsador y control fisico", "Pulsador de pared, maniobra manual y cableado de control (15)", 50),
    ("INTEGRACIONES", "Integraciones", "Alexa, Google Home, KNX y sistemas de terceros (11)", 60),
    ("INSTALACION", "Instalacion y montaje", "Montaje, conexionado y puesta en marcha en obra (7)", 70),
    ("HARDWARE", "Rotura y averia fisica", "Dano fisico, componente averiado y reposicion (6)", 80),
    ("OTRO", "Sin clasificar / incidencia nueva", "Entrada para lo que no encaja en ningun grupo; candidata a grupo nuevo (30)", 999),
]


def upgrade() -> None:
    """Crea la taxonomia de grupos de incidencia y la relaciona con los tickets."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_groups_code'), 'incident_groups', ['code'], unique=True)
    op.create_index(op.f('ix_incident_groups_id'), 'incident_groups', ['id'], unique=False)
    op.create_table('ticket_grupos_secundarios',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['incident_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_sat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'grupo_id')
    )
    op.add_column('tickets_sat', sa.Column('grupo_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tickets_sat_grupo_id'), 'tickets_sat', ['grupo_id'], unique=False)
    op.create_foreign_key(None, 'tickets_sat', 'incident_groups', ['grupo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Siembra: sin grupos la tabla no sirve de nada, y estos son los que los
    # datos reales respaldan. Se pueden editar despues desde la administracion.
    op.bulk_insert(
        sa.table(
            "incident_groups",
            sa.column("code", sa.String),
            sa.column("name", sa.String),
            sa.column("description", sa.Text),
            sa.column("is_active", sa.Boolean),
            sa.column("sort_order", sa.Integer),
        ),
        [
            {"code": c, "name": n, "description": d, "is_active": True, "sort_order": o}
            for c, n, d, o in GRUPOS_INICIALES
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets_sat', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_sat_grupo_id'), table_name='tickets_sat')
    op.drop_column('tickets_sat', 'grupo_id')
    op.drop_table('ticket_grupos_secundarios')
    op.drop_index(op.f('ix_incident_groups_id'), table_name='incident_groups')
    op.drop_index(op.f('ix_incident_groups_code'), table_name='incident_groups')
    op.drop_table('incident_groups')
    # ### end Alembic commands ###
