"""persistir respuestas del cuestionario

Crea cuestionarios_asistencia. Hasta ahora el cuestionario de asistencia se
evaluaba y las respuestas se descartaban: el tecnico rellenaba doce bloques,
recibia un diagnostico y no quedaba rastro de que habia contestado.

Se guarda el envio entero en respuestas_json, no una columna por pregunta: las
preguntas van a cambiar con G3.2 y una tabla con ochenta columnas quedaria
obsoleta a la primera. Los cuatro campos sueltos son los que se filtran a menudo.

ticket_id es SET NULL para que borrar un ticket no borre la evidencia de lo que
se contesto antes de crearlo.

Revision ID: bbd75c7ee2bc
Revises: 6cadde48eeca
Create Date: 2026-09-14 12:19:11.190640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd75c7ee2bc'
down_revision: Union[str, Sequence[str], None] = '6cadde48eeca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cuestionarios_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.String(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('dispositivo', sa.String(), nullable=True),
    sa.Column('area_incidencia', sa.String(), nullable=True),
    sa.Column('diagnostico_titulo', sa.String(), nullable=True),
    sa.Column('confianza', sa.Float(), nullable=True),
    sa.Column('respuestas_json', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_sat.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cuestionarios_asistencia_area_incidencia'), 'cuestionarios_asistencia', ['area_incidencia'], unique=False)
    op.create_index(op.f('ix_cuestionarios_asistencia_dispositivo'), 'cuestionarios_asistencia', ['dispositivo'], unique=False)
    op.create_index(op.f('ix_cuestionarios_asistencia_fecha'), 'cuestionarios_asistencia', ['fecha'], unique=False)
    op.create_index(op.f('ix_cuestionarios_asistencia_id'), 'cuestionarios_asistencia', ['id'], unique=False)
    op.create_index(op.f('ix_cuestionarios_asistencia_ticket_id'), 'cuestionarios_asistencia', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cuestionarios_asistencia_ticket_id'), table_name='cuestionarios_asistencia')
    op.drop_index(op.f('ix_cuestionarios_asistencia_id'), table_name='cuestionarios_asistencia')
    op.drop_index(op.f('ix_cuestionarios_asistencia_fecha'), table_name='cuestionarios_asistencia')
    op.drop_index(op.f('ix_cuestionarios_asistencia_dispositivo'), table_name='cuestionarios_asistencia')
    op.drop_index(op.f('ix_cuestionarios_asistencia_area_incidencia'), table_name='cuestionarios_asistencia')
    op.drop_table('cuestionarios_asistencia')
    # ### end Alembic commands ###
